apiVersion: skaffold/v4beta10
kind: Config
build:
  artifacts:
    - image: haseebudeen/auth
      context: auth
      sync:
        manual:
          - src: "src/**/*.ts"
            dest: .
      docker:
        dockerfile: Dockerfile
    - image: haseebudeen/ticketing-client
      context: client
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: "**/*.js"
            dest: .
    - image: haseebudeen/tickets
      context: tickets
      sync:
        manual:
          - src: "src/**/*.ts"
            dest: .
      docker:
        dockerfile: Dockerfile
    - image: haseebudeen/orders
      context: orders
      sync:
        manual:
          - src: "src/**/*.ts"
            dest: .
      docker:
        dockerfile: Dockerfile
    - image: haseebudeen/expiration
      context: expiration
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: "src/**/*.ts"
            dest: .
    - image: haseebudeen/payments
      context: payments
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: "src/**/*.ts"
            dest: .
  local:
    push: false
manifests:
  rawYaml:
    - ./infra/k8s/*
    - ./infra/k8s-dev/*
deploy:
  kubectl: {}
